buffer = input("Digite algo: ")
print(f"Tipo primitivo {type(buffer)}")
print(f"Só tem espaços? {buffer.isspace()}")
print(f"É numérico? {buffer.isnumeric()}")
print(f"É alfabético? {buffer.isalpha()}")
print(f"É alfanumérico? {buffer.isalnum()}")
print(f"Tem dígitos? {buffer.isdigit()}")
print(f"Está em maiúsculas? {buffer.isupper()}")
print(f"Está em minúsculas? {buffer.islower()}")
print(f"Está capitalizado? {buffer.istitle()}")
